-- FROZEN BASELINE — do not edit this file.
-- All future schema changes go in new 0002+ migration files.
-- Initial schema for contractor quote platform (D1 / SQLite)

-- Contractors (one row per tenant)
CREATE TABLE contractors (
  id TEXT PRIMARY KEY,
  slug TEXT NOT NULL UNIQUE,         -- URL-safe identifier, e.g. 'central-cabinets' → {slug}.contractorquote.work
  name TEXT NOT NULL,
  email TEXT,
  phone TEXT,
  address TEXT,
  website_url TEXT,
  license_number TEXT,
  logo_url TEXT,
  calendar_url TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);

-- Customers (one per unique email per contractor)
CREATE TABLE customers (
  id TEXT PRIMARY KEY,
  contractor_id TEXT NOT NULL REFERENCES contractors(id),
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  phone TEXT NOT NULL,
  cell TEXT,
  how_did_you_find_us TEXT,
  referred_by_contractor TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now')),
  UNIQUE(contractor_id, email)
);

-- Quotes
-- NOTE: contractor_id is denormalized from customers for fast tenant isolation checks
CREATE TABLE quotes (
  id TEXT PRIMARY KEY,
  customer_id TEXT NOT NULL REFERENCES customers(id),
  contractor_id TEXT NOT NULL REFERENCES contractors(id),
  schema_version INTEGER NOT NULL DEFAULT 1,
  -- Job site (may differ from customer address)
  job_site_address TEXT NOT NULL,
  property_type TEXT NOT NULL,
  budget_range TEXT NOT NULL,
  -- Scope blob (all project scope fields as JSON, versioned by schema_version)
  scope JSON,
  -- Quote flow
  public_token TEXT NOT NULL UNIQUE, -- 256-bit crypto-random for magic link (per quote)
  -- Status lifecycle
  status TEXT NOT NULL DEFAULT 'draft', -- draft | lead | reviewing | site_visit_requested | site_visit_scheduled | site_visit_completed | estimate_requested | estimate_sent | accepted | rejected | closed
  submitted_at TEXT,                    -- set when draft → lead (customer hits Submit)
  deleted_at TEXT,                      -- set when anonymized (right-to-delete), null = active
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);

-- Staff members (per contractor team)
CREATE TABLE staff (
  id TEXT PRIMARY KEY,
  contractor_id TEXT NOT NULL REFERENCES contractors(id),
  clerk_user_id TEXT,              -- linked when they accept invite, nullable until then
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'admin', -- 'owner' | 'admin' | 'estimator' | 'field_tech'
  phone TEXT,
  active INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now')),
  UNIQUE(contractor_id, email)
);

-- Quote activity feed (unified timeline: status changes, notes, photo events, edits)
CREATE TABLE quote_activity (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  quote_id TEXT NOT NULL REFERENCES quotes(id),
  contractor_id TEXT NOT NULL REFERENCES contractors(id),
  staff_id TEXT REFERENCES staff(id), -- null for system/customer actions
  type TEXT NOT NULL,              -- 'status_change' | 'note' | 'photo_added' | 'photo_removed' | 'quote_edited' | 'estimate_sent' | 'email_sent'
  content TEXT,                    -- note text or change description
  old_value TEXT,                  -- for status_change: previous status enum key
  new_value TEXT,                  -- for status_change: new status enum key
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

-- Photos (metadata — actual files in R2 or local mock storage)
-- NOTE: contractor_id denormalized from quotes for fast tenant isolation
CREATE TABLE photos (
  id TEXT PRIMARY KEY,
  quote_id TEXT NOT NULL REFERENCES quotes(id),
  contractor_id TEXT NOT NULL REFERENCES contractors(id),
  storage_key TEXT NOT NULL,        -- R2 key: {contractor_id}/{quote_id}/{id}.{ext}
  filename TEXT NOT NULL,           -- original filename from upload
  content_type TEXT NOT NULL,       -- e.g. image/jpeg, image/png, image/heic
  size INTEGER NOT NULL,            -- file size in bytes
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

-- Appointments
-- NOTE: contractor_id denormalized from quotes for fast tenant isolation
CREATE TABLE appointments (
  id TEXT PRIMARY KEY,
  quote_id TEXT NOT NULL REFERENCES quotes(id),
  contractor_id TEXT NOT NULL REFERENCES contractors(id),
  customer_id TEXT NOT NULL REFERENCES customers(id),
  scheduled_by TEXT REFERENCES staff(id), -- which staff member scheduled it
  slot_date TEXT NOT NULL,
  slot_period TEXT NOT NULL CHECK (slot_period IN ('morning', 'afternoon', 'evening')),
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'confirmed', 'cancelled')),
  notes TEXT,
  cancelled_at TEXT,               -- when cancelled, for audit trail
  cancelled_by TEXT REFERENCES staff(id),
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);

-- Data deletion audit log (CCPA / right-to-delete compliance)
-- Stores metadata about what was deleted, but NOT the deleted PII itself.
CREATE TABLE data_deletion_log (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  contractor_id TEXT NOT NULL REFERENCES contractors(id),
  request_type TEXT NOT NULL,  -- 'ccpa' | 'customer' | 'contractor'
  requested_by TEXT NOT NULL,  -- staff ID or 'customer' or 'system'
  email_hash TEXT NOT NULL,    -- SHA-256 hash of the deleted email (for dedup, not re-identification)
  quotes_deleted INTEGER NOT NULL DEFAULT 0,
  photos_deleted INTEGER NOT NULL DEFAULT 0,
  appointments_deleted INTEGER NOT NULL DEFAULT 0,
  activity_records_deleted INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

-- Indexes for common queries
CREATE INDEX idx_contractors_slug ON contractors(slug);
CREATE INDEX idx_customers_contractor ON customers(contractor_id);
CREATE INDEX idx_customers_email ON customers(contractor_id, email);
CREATE INDEX idx_quotes_customer ON quotes(customer_id);
CREATE INDEX idx_quotes_contractor ON quotes(contractor_id);
CREATE INDEX idx_quotes_status ON quotes(status);
CREATE INDEX idx_quotes_budget ON quotes(budget_range);
CREATE INDEX idx_quotes_token ON quotes(public_token);
CREATE INDEX idx_quotes_created ON quotes(created_at);
CREATE INDEX idx_quotes_submitted ON quotes(submitted_at);
CREATE INDEX idx_quotes_active ON quotes(contractor_id, deleted_at); -- fast filter for non-deleted
CREATE INDEX idx_staff_contractor ON staff(contractor_id);
CREATE INDEX idx_activity_quote ON quote_activity(quote_id, created_at);
CREATE INDEX idx_activity_staff ON quote_activity(staff_id);
CREATE INDEX idx_photos_quote ON photos(quote_id);
CREATE INDEX idx_photos_contractor ON photos(contractor_id);
CREATE INDEX idx_appointments_contractor ON appointments(contractor_id);
CREATE INDEX idx_appointments_date ON appointments(slot_date);
CREATE INDEX idx_appointments_quote ON appointments(quote_id);
CREATE INDEX idx_appointments_customer ON appointments(customer_id);
CREATE INDEX idx_deletion_log_contractor ON data_deletion_log(contractor_id);
CREATE INDEX idx_deletion_log_created ON data_deletion_log(created_at);
CREATE INDEX idx_deletion_log_email_hash ON data_deletion_log(email_hash);

-- Seed: default contractor for dev
INSERT INTO contractors (id, slug, name, logo_url) VALUES (
  'contractor-001',
  'central-cabinets',
  'Central Cabinets',
  NULL
);
